### PR TITLE
GUI-Based Tic Tac Toe Game with Python

### LINKED ISSUE #186: GUI-based Tic Tac Toe Game using Python
# Description
I would like to create a tic tac toe game using `tkinter` library in python.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by madhavmehndiratta**
# Description
GUI based Tic Tac Toe Game

Fixes #186 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
no need to add requirements.txt , Tkinter is in-built

**Comment by madhavmehndiratta** [comment]
> no need to add requirements.txt , Tkinter is in-built

Removed

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
The play again feature is not working , instead of restarting the game it exits it.

The same issue with Restart button

**Comment by tusharnankani** [comment]
> The play again feature is not working , instead of restarting the game it exits it.
> 
> The same issue with Restart button

@AdityaJ7 was this issue fixed?

**Comment by AdityaJ7** [comment]
> > The play again feature is not working , instead of restarting the game it exits it.
> > The same issue with Restart button
> 
> @AdityaJ7 was this issue fixed?

Yes, it exists on windows because the paths were set as per Linux path representation
So consider it fixed

**Pull request merged**
