### PR TITLE
Add jaesharma

### PR DESCRIPTION
**Pull request by jaesharma**
Added a new portscanner script with README under the miscellaneous folder.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
> Added a new portscanner script with README under the miscellaneous folder.

Follow the PR tempelate

**Comment by AdityaJ7** [comment]
> > Added a new portscanner script with README under the miscellaneous folder.
> 
> Follow the PR tempelate

Create an issue before creating a pr

**Comment by jaesharma** [comment]
> > > Added a new portscanner script with README under the miscellaneous folder.
> > 
> > 
> > Follow the PR tempelate
> 
> Create an issue before creating a pr

ok, opening a new issue on this.

**Comment by jaesharma** [comment]
hey @AdityaJ7 , its my first PR so I'm a bit confused. Is it allowed if I create an issue myself, and request a pull request on the same? or i need to get assigned by someone to work on something?!

**Comment by AdityaJ7** [comment]
> hey @AdityaJ7 , its my first PR so I'm a bit confused. Is it allowed if I create an issue myself, and request a pull request on the same? or i need to get assigned by someone to work on something?!

Create an issue, if it is not a duplicate then someone will assign it to you after that you can create a PR 

THANKS

**Pull request closed without merging**
