### PR TITLE
[ADD] Soccer Standings CLI script

### LINKED ISSUE #460: [New Script] Soccer League Table CLI for major leagues
# Description
Display current standings in the league requested by using a free API or scraping a webpage.
## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by MaheshBharadwaj**
# Description

Added script for displaying soccer standings of major football leagues

Fixes #460 

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
hey @MaheshBharadwaj thanks for the pr can you change the location of your folder to API , as you have used an API in this script , Thanks

**Comment by MaheshBharadwaj** [comment]
> hey @MaheshBharadwaj thanks for the pr can you change the location of your folder to API , as you have used an API in this script.

Moved the files to `API` folder

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @MaheshBharadwaj for code

**Review by tusharnankani — APPROVED** [review]

**Comment by tusharnankani** [comment]
Isn't the `mergify` bot working? @AdityaJ7

**Comment by AdityaJ7** [comment]
@all-contributors please add @MaheshBharadwaj for code

**Pull request merged**
