### PR TITLE
Reddit Scraper

### PR DESCRIPTION
**Pull request by danieljo09**
# Description

A short summary of what is included in your Pull Request.

Fixes #(31)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
Please follow the PR template @danieljo09 and also mention the related issue else it will be marked as spam

**Comment by danieljo09** [comment]
@AdityaJ7  thank you sm. its late for me rn, so ill fix my pr up tomorrow!

**Review by tusharnankani — CHANGES_REQUESTED** [review]
- Please add a screenshot of the working script, and add it to the README as well.
- Create a requirements.txt file and add `pandas`, `shaw` and `config` to it.
- Comment your code for better understanding.
- Remove unnecessary blank lines from your code,

**Review by tusharnankani — APPROVED** [review]

**Comment by danieljo09** [comment]
@AdityaJ7  How does this look?

**Comment by AdityaJ7** [comment]
@all-contributors please add @danieljo09 for code

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @danieljo09 for code

**Pull request merged**
