### PR TITLE
Telegram Weather Bot

### LINKED ISSUE #285: Telegram Bot for Weather Info
# Description
A telegram bot which will provide real time weather information to the user using a weather API in python

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by namanshah01**
# Description

Telegram bot that provides real time weather info of a particular city using Open Weather Maps API

Fixes #285

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
@namanshah01 please refer to the deep source error and try to fix them, if you need help comment here,

Thanks

**Comment by AdityaJ7** [comment]
@namanshah01 remove the pycache files and will merge it.

NIce Job

**Comment by namanshah01** [comment]
Thank you @AdityaJ7 , is this going to be merged?

**Comment by AdityaJ7** [comment]
> Thank you @AdityaJ7 , is this going to be merged?

Yes just remove the pycache files

**Comment by namanshah01** [comment]
Yeah just a minute

**Comment by AdityaJ7** [comment]
@all-contributors please add @namanshah01 for code

**Pull request merged**
