### PR TITLE
Added IMDB Spider

### PR DESCRIPTION
**Pull request by Apex-code**
# Description

IMDB scrapy spider 

Fixes #(issue_no)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by chavarera — CHANGES_REQUESTED** [review]
Some files are missing please recheck with your working build and update missing files

**Comment by Apex-code** [comment]
Sorry for that my laptop behaving weird since morning I'll fix this tomorrow.

**Comment by Apex-code** [comment]
> @Apex-code
> Some files are missing please recheck with your working build and update missing files.
> 
> Even some check get failed please look into it

@chavarera sir fixed all the errors now it's working fine

**Review by chavarera — APPROVED** [review]

**Comment by Apex-code** [comment]
@chavarera i need to change anything ? everything good?

**Review by Apex-code — COMMENTED** [review]
Updated Pipleline.py

**Comment by AdityaJ7** [comment]
@all-contributors please add @Apex-code for code

**Pull request merged**
