### PR TITLE
added face-detection script in Miscellaneous

### LINKED ISSUE #18: Face Detection in Python Using a Webcam
# Description

Write a basic script to detect faces in webcam using haar cascade. 

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [ ] I have checked all the existing projects, before submitting a new project issue.
- [ ] I have checked previous issues to avoid duplicates.
- [ ] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by MitanshiKshatriya**
# Description

A short summary of what is included in your Pull Request.

Fixes #18 

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
@MitanshiKshatriya is it possible to use a link which contains the XML that you have used instead u including the XML in the repo?

So that the size of the repo can be kept minimum?

If yes then please do that.

Everything else works fine, Good Job

**Comment by MitanshiKshatriya** [comment]
As far as I know for the script to work the XML file needs to be in local memory. I can remove the XML file and include steps in README.md to download the XML file. Should I do that?

**Comment by chavarera** [comment]
> As far as I know for the script to work the XML file needs to be in local memory. I can remove the XML file and include steps in README.md to download the XML file. Should I do that?

@MitanshiKshatriya thank you for contributing to open source

this repository contains lots of project so we restricting contributors to upload large size file it will help new contributor to clone this repository easily

Suggestions:
```
upload cascade file on any public accessible cloud ,server
and in readme file  add steps to download that 
```

**Comment by AdityaJ7** [comment]
@all-contributors please add @MitanshiKshatriya for code

**Pull request merged**
