### PR TITLE
Amazon Product Price Scraper and News Headlines Scraper 

### PR DESCRIPTION
**Pull request by ShantanuTaro**
# Description

A short summary of what is included in your Pull Request.
Added 2 new Python Scraper Programs.
1. Amazon Price Scraper.
2. News Scraper

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
Refer other scripts in the project for the correct template of the requirements.txt file.

In the future try to make separate prs if you want to add multiple scripts

**Comment by Apex-code** [comment]
Add readme.md to both files
Add working/sample screenshot
Edit requirements.text
 and hide you API key from news_headlines_scraper.py

**Comment by AdityaJ7** [comment]
> Add readme.md to both files
> Add working/sample screenshot
> Edit requirements.text
> and hide you API key from news_headlines_scraper.py

Follow these tips as well @ShantanuTaro

**Comment by ShantanuTaro** [comment]
> > Add readme.md to both files
> > Add working/sample screenshot
> > Edit requirements.text
> > and hide you API key from news_headlines_scraper.py
> 
> Follow these tips as well @ShantanuTaro and next time before creating a pull request please open an issue related to it
> 
> Thanks

Worked on the above queries and solved them.

**Review by Apex-code — APPROVED** [review]

**Review by Apex-code — APPROVED** [review]

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @ShantanuTaro for code

**Pull request merged**
