### PR TITLE
A Sudoku Solver python script added

### LINKED ISSUE #253: Python script to solve the Sudoku efficently
# Description

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by jaesharma**
# Description
A python script to solve the sudoku.

Fixes #253 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
fix the merge conflicts

**Comment by jaesharma** [comment]
I don't understand, can you help me with this, what exactly i need to change. The portscanner folder does not exist on the branch. and it says there is conflict in portscanner files. So should I add portscanner again on this branch ?!

**Comment by jaesharma** [comment]
ok i think it is fixed, let me know if something is still off.

**Comment by AdityaJ7** [comment]
@jaesharma  your port scanner stuff is included in it remove that

**Comment by AdityaJ7** [comment]
again merge conflicts are coming, close this or and make a fresh one for the sudoku solver if u are unable to resolve merge conflicts

**Comment by jaesharma** [comment]
@AdityaJ7 So in this commit i removed portscanner & there are conflicts again. There was no conflict on previous conflict, should i portscanner folder again?

**Comment by AdityaJ7** [comment]
> @AdityaJ7 So in this commit i removed portscanner & there are conflicts again. There was no conflict on previous conflict, should i portscanner folder again?

portscanner exists already

**Pull request closed without merging**
