### PR TITLE
Stock Scraper feature

### LINKED ISSUE #51: stock scraper
# Description
Scrape the S&P 500 Companies list from Wikipedia, Yahoo Finance, etc., then output the data.
Get stock prices

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by antoniouaa**
# Description
The script fetches the company names and symbols for the S&P500 companies off of Wikipedia and then uses the `yfinance` library to grab financial information for them for the last 3 months. 

The script saves a file to the disk with the symbols and names of the S&P500 companies and then asks the user whether to save the data for each company to the disk or not.

Fixes #51

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Good Job @antoniouaa just add some comments and change the name of your folder to something better like Stock scraper or whatever you like. everything else works fine

**Comment by tusharnankani** [comment]
Please add a working screenshot, of the script.

**Comment by antoniouaa** [comment]
I'm not sure what you mean by working screenshot of the script

**Comment by AdityaJ7** [comment]
> I'm not sure what you mean by working screenshot of the script

You can refer the existing scripts in this repo for better clarity

**Comment by antoniouaa** [comment]
Just an FYI, that linter error is not from my branch

**Comment by AdityaJ7** [comment]
> Just an FYI, that linter error is not from my branch

FYI it is in your branch, it is not a fatal error it is just a suggestion to improve performance
Capture

**Comment by AdityaJ7** [comment]
@all-contributors please add @antoniouaa for code

**Review by tusharnankani — COMMENTED** [review]
Great work @antoniouaa! 👍🏻 

Expecting more contributions from your end!

**Pull request merged**
