### PR TITLE
Added CodeChef Scraper

### LINKED ISSUE #9: Scrape CodeChef Problem Statement and store it as a text file
# Description

Write a script that takes a problem code, scrapes the concerned problem statement and stores it in a text file

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by officialpm**
# Description

Takes a **[`CodeChef Problem Code`](https://www.codechef.com)** as a **Command-Line Argument**, scrapes the appropriate problem statement, and saves it to a text file.

Fixes #9

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by tusharnankani — CHANGES_REQUESTED** [review]
- Please comment on your code for better understanding.
- Remove unnecessary empty lines from the code.
- If possible, just add a sample .txt file.

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Hi @officialpm Good Job, just make the changes as requested by Tushar and we'll merge it

**Comment by officialpm** [comment]
Hey @tusharnankani @AdityaJ7 🤘🏻

I have made the requested changes
 
- [x] Please comment on your code for better understanding.
- [x] Remove unnecessary empty lines from the code.
- [x]  If possible, just add a sample .txt file.

**Comment by AdityaJ7** [comment]
@all-contributors please add @officialpm for code

**Comment by AdityaJ7** [comment]
Good Job @officialpm

**Comment by officialpm** [comment]
> Good Job @officialpm

Thank you 😃 @AdityaJ7
Happy October 🤗

**Pull request merged**
