### PR TITLE
GUI based password generator added

### LINKED ISSUE #184: GUI Password Generator
# Description

Hi, I am Rohit Kumar Saini. I am new to open source contributions. I have created a GUI based Password generator. It has three types of passwords to be generated i.e. PIN, AlphaNumeric, Extreme Secure. 
So I want to start my contribution by adding this project of mine to your repo.
So can I add my project to it?
Thank you.

### PR DESCRIPTION
**Pull request by rockingrohit9639**
# Description

GUI password generator

Fixes #184 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- [X] New feature (non-breaking change which adds functionality)

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by tusharnankani** [comment]
Please follow the PR template. Which issue are you referring to? 
If the issue is not present, open an issue, and ask for it to be assigned.

Please follow the steps, otherwise, the PR will be marked INVALID.

**Comment by rockingrohit9639** [comment]
Sir please merge my PR or tell me if I have to do any changes?

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@rockingrohit9639 add a screenshot of the GUI where it generates a password

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
.

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 add a screenshot of the GUI where it generates a password

Done

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @rockingrohit9639 for code

**Pull request merged**
