### PR TITLE
[Add]:classic_snake_game

### LINKED ISSUE #126: Classic Snake game with Python
# Description

Create the classic snake game with python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by infern018**
# Description

A classic snake game with python

Fixes #126 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by infern018** [comment]
@AdityaJ7  please review...

**Comment by AdityaJ7** [comment]
Add a requirements.txt file

**Comment by infern018** [comment]
Done

**Comment by infern018** [comment]
thank you @AdityaJ7 , I didn't noticed the file game and version,
if there are any other changes please let me know,

otherwise please merge this Pull Request.

**Review by tusharnankani — APPROVED** [review]
Works well! @infern018 👍🏻 

Expecting more contributions from your end! ^_^

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @infern018 for code

**Pull request merged**
