### PR TITLE
Hash a given message using variety of algorithms

### PR DESCRIPTION
**Pull request by ShravanBhat**
# Description

A short summary of what is included in your Pull Request.

Fixes #(issue_no)

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by ShravanBhat** [comment]
Variety of hashing algorithms are covered in it.

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
please mention that variety - kind of algorithms used in the readme

and also please run your script through flake8 module 

follow these steps in your local environment
1.pip install flake8

2.flake8 <your python file>


It will give some errors and will tell u how to fix them

apply those changes and push the code 

If one function is getting too long then try to break it into multiple functions

For any doubts comment here on in our whatsapp group

Thanks

**Comment by ShravanBhat** [comment]
Changes done .

**Comment by ShravanBhat** [comment]
Can you please merge it with main repository?

**Comment by AdityaJ7** [comment]
@all-contributors please add @ShravanBhat for code

**Pull request merged**
