### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by aakashdinkar**
# Description

A short summary of what is included in your Pull Request.

Fixes #(issue_no)

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
@aakashdinkar which issue is this related to??

**Comment by aakashdinkar** [comment]
@AdityaJ7 
This is not related to any issue instead, I have added my own script which tells the exact location of entered place with proper longitude and latitude.

**Comment by AdityaJ7** [comment]
> @AdityaJ7
> This is not related to any issue instead, I have added my own script which tells the exact location of entered place with proper longitude and latitude.

Sorry but this kind of script already exists in our collection, that's why it is advised to first create an issue before making a PR

**Comment by aakashdinkar** [comment]
@AdityaJ7 I made the pr because first I checked your repo there was no script related to my script. Without even looking it to my script how can you set labels like spam or duplicate. If you have similar script show me coz I didn't find any.

**Comment by AdityaJ7** [comment]
> @AdityaJ7 I made the pr because first I checked your repo there was no script related to my script. Without even looking it to my script how can you set labels like spam or duplicate. If you have similar script show me coz I didn't find any.

Did you check the already existing issues? **I checked you script before marking those labels** and the usual practice is to first create an issue so that u don't make duplicates.

Check this [issue](https://github.com/Python-World/Python_and_the_Web/issues/155)
Check this [project](https://github.com/Python-World/python-mini-projects/tree/master/projects/Geocoding)

The thing you are trying to do in your script is called geocoding, we already have the same thing with two different approaches .

**Comment by AdityaJ7** [comment]
Check this [issue](https://github.com/Python-World/Python_and_the_Web/issues/31) it has been pinned to the repo.

That's why it is suggested to first create an issue so that you don't waste your time on creating something that already exists

**Comment by aakashdinkar** [comment]
@AdityaJ7  Ok thanks, from next time I'll first check the existing issue then will make pr accordingly.

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Ok thanks, from next time I'll first check the existing issue then will make pr accordingly.

OK, thanks for understanding, will be looking forward to your contribution

**Pull request closed without merging**
