### PR TITLE
Python script to convert Chmod permission to Symbolic/Numerical notations

### LINKED ISSUE #494: Python CHMOD simplifier
# Description
A script to give a detailed break-up of the CHMOD permissions used for unix based file systems to change permissions.

Eg.  input: 777
output:  rwxrwxrwx

Eg. 755
output: rwxr-xr-x

## Type of issue
- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:
- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by schezfaz**
# Description

A python script to convert CHMOD permissions from its symbolic notation to its numerical notation and vice versa.

Fixes #494 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Hi @schezfaz thanks for the contribution, the script works fine I just have two suggestions:

1. Please uncommit the requirements.txt file and add a screenshot of the script when executed through the command line. So you will have to make some changes in the Readme file also.

2. Please remove the extra space from the end of the file and just give one space there, 2 spaces must be given before the functions.

**Comment by schezfaz** [comment]
Hey @AdityaJ7! Apologies for the addition of the requirements.txt haha, force of habit. Please have another look, have incorporated the requested changes!!

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
> Hey @AdityaJ7! Apologies for the addition of the requirements.txt haha, force of habit. Please have another look, have incorporated the requested changes!!

No problem, Good job

**Review by tusharnankani — CHANGES_REQUESTED** [review]
Hi! 

Since this is a beginner-friendly repository, could you include what CHMOD is and some brief description about it? Attach references, if required!

**Comment by schezfaz** [comment]
Hi @tusharnankani! Sure, makes sense. Have added a small brief on what CHMOD is and its representation. LMKWYT!

**Review by AdityaJ7 — APPROVED** [review]

**Review by tusharnankani — COMMENTED** [review]
Looks good! 👍🏻 
Great work @schezfaz

**Pull request merged**
