### PR TITLE
Added a telegram bot which runs python code

### LINKED ISSUE #623: Run python expressions from telegram, Telegram Bot
# Description
This bot will execute a python expression and return the results.
Take a look at the GIF 

python_telegram

## Type of issue
- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by aahnik**
# A simple telegram bot that runs python code

RunPythonBot

# Description

Fixes #623 

[GitHub license](https://github.com/aahnik/lovely-telegram/blob/main/LICENSE) [made-with-python](https://www.python.org/)

- Run python expressions from telegram, Telegram Bot
- As described in issue #623 , the new bot is added
- On branch aahnik_runPythonBot

- This bot will execute a python expression and return the results.

Take a look at this GIF to understand better:

  
You may use pythonic expressions to easily calculate any complex problem. Or you may test your algorithms on the go.

>Click the gif to view full screen on Smartphone

runPython_bot

  
You can easily *deploy this bot* on [Python Anywhere](https://www.pythonanywhere.com/) or on your **local machine** by following the steps given in README.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

```
Changes to be committed:
	new file:   runPython_bot/.gitignore
	new file:   runPython_bot/Makefile
	new file:   runPython_bot/README.md
	new file:   runPython_bot/bot/__init__.py
	new file:   runPython_bot/bot/execute_code.py
	new file:   runPython_bot/bot/runPython_bot.py
	new file:   runPython_bot/requirements.txt
	new file:   runPython_bot/start.py
```

### CODE REVIEW

**Comment by aahnik** [comment]
@AdityaJ7 @fuzzmz @valterm @dingusagar @k1m0ch1 @arthuralmeida93 @MNISAR @antoniouaa @sandyjswl @malhotra-paritosh @chavarera @SuvamPrasd @Araon @symtalha14 

The bot is live and running.

Check it out now ☺️

http://t.me/runPython_bot

If the link does not work search
`@runPython_bot` in Telegram.

**Comment by AdityaJ7** [comment]
@aahnik very nice, just add some comments in your py files to make it a bit beginner friendly else everything else is awesome

**Comment by aahnik** [comment]
I have added docstrings with explanations and links to tutorials in my last commit https://github.com/Python-World/Python_and_the_Web/pull/624/commits/5668ad1524cf246455b11dea4cfaf193d864eafe

**Review by aahnik — COMMENTED** [review]
I have reviewed the entire code , and have found no problems.

 The deployment is also successful and the bot is running smoothly.

Any suggestions for improving the performance of the bot is most welcome ! 😀

**Review by AdityaJ7 — APPROVED** [review]

**Comment by aahnik** [comment]
My work is complete, you may try running the following on the already deployed bot


image

Check out @runPython_bot

Run Python code from telegram chat

**Review by tusharnankani — APPROVED** [review]

**Comment by tusharnankani** [comment]
@allcontributors please add @aahnik for code

**Comment by aahnik** [comment]
Thanks a lot @AdityaJ7 and @tusharnankani for accepting my pull request.

This was really a fun and enjoyable learning experience.

I hope to contribute more code in future.

**Comment by tusharnankani** [comment]
@aahnik 
Expecting more contributions from your end! 👍🏻 
Keep it up! ^_^

**Pull request merged**
