### PR TITLE
Project euler problems scraper

### LINKED ISSUE #8: Scrape all the problems from Project Euler
# Description

Write a script to scrape all the problems present in the Project Euler website and store them in a csv or text file.
You can check this [website]( https://projecteuler.net/archives) for reference

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by pratik-choudhari**
# Description
A scraper built in python to scrape project euler problems

Fixes #8 

## Type of change
- [X] New feature (non-breaking change which adds functionality)
# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
Hey @AdityaJ7 , my name was not added to contributors is it because of the github action failing?

**Comment by AdityaJ7** [comment]
> Hey @AdityaJ7 , my name was not added to contributors is it because of the github action failing?

no, I guess it has to do something with the organization settings, will look for a fix when someone else makes a pr and they are not added to the contributor.!!

**Comment by pratik-choudhari** [comment]
okay✌

**Comment by AdityaJ7** [comment]
@all-contributors please add @pratik-choudhari

**Comment by AdityaJ7** [comment]
@all-contributors please add @jakebolam for code

**Comment by AdityaJ7** [comment]
@all-contributors please add @partik-choudhari for code

**Comment by AdityaJ7** [comment]
@all-contributors please add @pratik-choudhari  for code

**Pull request merged**
