### PR TITLE
I did some sorting.

### PR DESCRIPTION
**Pull request by rishu1722**
# Description

I did some sorting which was necessary.

.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [] I have included a requirements.txt file (if external libraries are required.)
- [] My changes do not produce any warnings.
- [] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by chavarera — CHANGES_REQUESTED** [review]
@rishu1722  Thanks for contributing

Suggestions
```
Add Proper readme.md file
Put your all code in one another directory instead of pushing to bots directory
Add requirements.txt file
Add meaningful commit message
```

**Review by tusharnankani — CHANGES_REQUESTED** [review]
Which issue are you referring to? @rishu1722 

If the issue is not mentioned, create it [here](https://github.com/Python-World/Python_and_the_Web/issues/new)!

Also, the PR description doesn't match the code!

Please follow the [guidelines](https://github.com/Python-World/Python_and_the_Web#how-to-contribute)!

**Comment by rishu1722** [comment]
Ok I will see it after some time.

**Comment by AdityaJ7** [comment]
Closing this, for now, please follow the guidelines and create a proper PR

**Pull request closed without merging**
