### PR TITLE
Added Image to base64 convertor and vice-versa

### PR DESCRIPTION
**Pull request by pranav6670**
# Description
Implemented a converter that converts an image into base64 encoding and also decoding it writes to the image. Also, added a metric popularly called a structural similarity index(SSI) to compare original and new(generated) image.

Fixes #(47)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by pranav6670** [comment]
Please review the PR @AdityaJ7 @chavarera. Thank You!

**Review by chavarera — APPROVED** [review]

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @pranav6670 for code

**Comment by pranav6670** [comment]
Please add a hacktoberfest-accepted label. Thank You @AdityaJ7 @chavarera

**Comment by AdityaJ7** [comment]
> Please add a hacktoberfest-accepted label. Thank You @AdityaJ7 @chavarera

only required from 3 October yours was merged before that

**Pull request merged**
