### PR TITLE
COVID-19 stats

### PR DESCRIPTION
**Pull request by YASHBRO**
# COVID-19 scraper

Unlike other the scraper, with this one, you can even search for the stats for any particular country/state.
This script, after running, displays the following things:
1. COVID-19 stats including total cases, total deaths, people recovered.
2. Stats of top-10 countries suffering from this pandemic.
3. You can even search stats for any country or any state, searching a city name will most probably give you the stats of that state and that country in which the city exists. 

You can search an infinite number of times without exiting the script.

Fixes [330](https://github.com/Python-World/Python_and_the_Web/issues/330 )

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by YASHBRO** [comment]
**Please add the tag `Hacktoberfest accepted` if you choose to merge this pull request**

**Comment by YASHBRO** [comment]
This took me so much time because, before this, I was working on the other issue [351](#351).

And that was a successful [pull request](#379)

**Comment by AdityaJ7** [comment]
@YASHBRO please add a requirements.txt fiel

**Comment by YASHBRO** [comment]
> @YASHBRO please add a requirements.txt file

Oops sorry, just a sec

**Review by AdityaJ7 — APPROVED** [review]

**Pull request merged**
