### PR TITLE
Geo code API

### LINKED ISSUE #155: Google maps API
# Description

You enter the address and it will mark its coordinate on maps on website, according to google maps, will use google maps api to get coordinates and map

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by Mysterious-Owl**
# Description

Created the Geocode API code using Maps API, since Google maps geocode is paid, I used open cage API, but map is of google map for website

Fixes #155

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by Mysterious-Owl** [comment]
@tusharnankani Now check

**Comment by AdityaJ7** [comment]
@Mysterious-Owl fix deepsource issues

**Comment by Mysterious-Owl** [comment]
> @Mysterious-Owl fix deepsource issues

I did what it asked me to do, but I can't understand why it's not fixed yet, any suggestions?

**Comment by aakashdinkar** [comment]
i would like to make it generic. It seems this code will work for few places only, i have script which will work on any places even work on misspelled places.

**Pull request merged**
