### PR TITLE
fixes issue #230

### LINKED ISSUE #230: News App
A News Website which shows the top news all categories and also with the feature of personalising your own feed and bookmarking important links
## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [ X] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [ X] I have checked previous issues to avoid duplicates.
- [ X] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by KhushiGangopadhyay**
Newsapp based on django framework of python

Fixes #230 
Made the Newsapp, couldnt add the feature of bookmarking instead added a new feature of changing colour mode, the app uses  api from  https://newsapi.org/

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X ] I have named my files and folder, according to this project's guidelines.
- [X ] My code follows the style guidelines of this project.
- [ X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X ] I have included a requirements.txt file (if external libraries are required.)
- [X ] My changes do not produce any warnings.
- [X ] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by KhushiGangopadhyay** [comment]
@AdityaJ7 Can you please tell me what to do to fix this issue

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Can you please tell me what to do to fix this issue

Hi, sorry for the delay, I'll check and fix it

**Comment by KhushiGangopadhyay** [comment]
removed all the unwanted libraries but I'm using newsapi.org 's  api I dont know why its showing error in the import statement in views file

**Comment by AdityaJ7** [comment]
> removed all the unwanted libraries but I'm using newsapi.org 's api I dont know why its showing error in the import statement in views file

ok I'll check the issue, please remove the  __pycache__ files also

**Comment by KhushiGangopadhyay** [comment]
okay

**Comment by KhushiGangopadhyay** [comment]
Can anyone please help me , I'm a newbie and I really don't know how to solve this error , thank you in advance :)

**Comment by Anshul275** [comment]
@KhushiGangopadhyay  In "views.py" file  in line 2 -> from newsapi import NewsApiClient
NewsApiClent is imported but never used.
So remove that line from your code.

You can also head to the details section across each error to know where is the error.
Happy to Help :)

**Comment by AdityaJ7** [comment]
@KhushiGangopadhyay sorry for the dealy @KhushiGangopadhyay I have fixed your issue and now merging it. Thanks for the contribution and for having patience.

Will be looking forward to more contributions from your side

Thanks again,

**Comment by AdityaJ7** [comment]
@all-contributors please add @KhushiGangopadhyay for code

**Comment by KhushiGangopadhyay** [comment]
@AdityaJ7 @Anshul275 Thank you so much!!!!!! :)

**Pull request merged**
