### PR TITLE
Fake news detection web application

### PR DESCRIPTION
**Pull request by asiskumarroy**
# Description

A fake news detection web app built using flask and NLTK to detect fake news regarding US presidential election 2016

Fixes #(issue_no)

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by asiskumarroy** [comment]
there were a few errors in my code so i had to debug them which made me repeatedly open and close the issue,since i am new to github.Now everything is fine , hope you get my code

**Comment by AdityaJ7** [comment]
remove pycache and checkpoints folder

**Comment by asiskumarroy** [comment]
okay

**Comment by asiskumarroy** [comment]
i have removed the pycache and checkpoints folder.The error checks are
rectified as well.A readme file,requirements.txt and screenshot of working
is also provided.

**Pull request closed without merging**
