### PR TITLE
adding micheline resturent scraper

### LINKED ISSUE #114: Michelin star restaurants scraper
# Description

website to scraper https://guide.michelin.com/en/restaurants

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by killerpanda101**
# Description

Michelin resturent data scraper

Fixes #114

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by tusharnankani** [comment]
Please follow the Code of Conduct.
Which issue is this PR referred to? Please link your PR to the respective issue, or create one [here](https://github.com/Python-World/Python_and_the_Web/issues).

**Comment by killerpanda101** [comment]
sorry should have mentioned it
Michelin star restaurants scraper #114
The issue was closed by the GitHub bot, let me know if you want me to create a new one.

**Comment by AdityaJ7** [comment]
@killerpanda101 add a few more comments and refer to existing scripts to check the proper requirements file format.

Enclose the main function call under --  `if __name__ == "__main__":`

Try fixing the deep source stuff, if you are unable to fix them, i'll help you.

**Review by tusharnankani — CHANGES_REQUESTED** [review]
> @killerpanda101 add a few more comments and refer to existing scripts to check the proper requirements file format.
Enclose the main function call under -- if __name__ == "__main__":
Add a screenshot of the script in action, like how to execute it from the cli and what kinda output it gives, stuff like that.

Hope you are working on this^

Also, please comment on your code for better understanding and remove unnecessary empty lines. Also, please add a bit more description of your script in the README.

**Review by tusharnankani — APPROVED** [review]

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@allcontributors please add @killerpanda101 for code

**Pull request merged**
