### PR TITLE
Torrent Searcher Bot

### PR DESCRIPTION
**Pull request by Apex-code**
# Description

A telegram bot for getting torrent magnet link

Fixes #(issue_no)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by Apex-code** [comment]
@AdityaJ7 @chavarera

**Comment by AdityaJ7** [comment]
> @AdityaJ7 @chavarera

You can remove the commented code

**Comment by Apex-code** [comment]
> > @AdityaJ7 @chavarera
> 
> You can remove the commented code

Done !!

**Comment by Apex-code** [comment]
> > @AdityaJ7 @chavarera
> 
> You can remove the commented code

Fixed Sir

**Comment by Apex-code** [comment]
> > @AdityaJ7 @chavarera
> 
> You can remove the commented code

DONE

**Pull request merged**
