### PR TITLE
Added 'FLAMES-game' folder to Scripts/Miscellaneous which implement the 'FLAMES' game using python script

### PR DESCRIPTION
**Pull request by Saujanya0910**
# Description

Added a folder 'FLAMES-game' containing 'flames_game.py' script, 'README.md' having details and screenshots.

Fixes #(#33 )

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
@Saujanya0910  Remove the extra files that you have committed your pull request must only contain what you have added!!
It must only contain 4 files
1. your script 
2. your readme 
3 screenshot1
4 screenshot2 

Remove all other 16 files from commit

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Remove unnecessary files

**Comment by Saujanya0910** [comment]
These aren't my commit, these are from the pull upstream. The other commits are from before my commits.

**Review by tusharnankani — APPROVED** [review]

**Comment by AdityaJ7** [comment]
> These aren't my commit, these are from the pull upstream. The other commits are from before my commits.

This happened because your fork was not up-to-date with our repo

before making changes in your forked repo please make sure it is up to date by running following commands:

1. git remote add upstream https://github.com/Python-World/Python_and_the_Web.git
2. git fetch upstream
3. git pull upstream master
4. git push 


Thanks

**Comment by Saujanya0910** [comment]
Before pushing my local repo to remote, I had updated my local repo as the upstream. What to do now ?

**Comment by AdityaJ7** [comment]
> Before pushing my local repo to remote, I had updated my local repo as the upstream. What to do now ?

I have fixed it now don't worry

**Comment by Saujanya0910** [comment]
Thank you, and sorry for the inconvenience.

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @Saujanya0910  for code

**Pull request merged**
