### PR TITLE
Passwords List Generator

### PR DESCRIPTION
**Pull request by madhavmehndiratta**
# Description

A Custom Wordlist Generator using Python #80

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by tusharnankani — CHANGES_REQUESTED** [review]
Hi @madhavmehndiratta 

The script works well. Good work! 👍🏻 

Changes:
- Please comment on your code, for better understanding.
- Explain what leet_mode, and print it, while you ask that question.

Suggestion
- A better name could be given to the project.

**Comment by madhavmehndiratta** [comment]
Hi @tusharnankani 
Thanks for reviewing the project, can you suggest a better name for the project?

**Comment by tusharnankani** [comment]
> Hi @tusharnankani
> Thanks for reviewing the project, can you suggest a better name for the project?

Hi! Since this project is on the lines of **Password** and not simply a random wordlist generator, then something on those lines.

**Comment by tusharnankani** [comment]
Please make the requested changes.

**Comment by madhavmehndiratta** [comment]
Hi, I have tried to comment my code (Though I am not at all good at it) Also, I think the code is clear that anyone with basic python knowledge can easily understand.

**Review by chavarera — APPROVED** [review]

**Comment by madhavmehndiratta** [comment]
It should not have any conflicts now

**Review by tusharnankani — APPROVED** [review]

**Comment by tusharnankani** [comment]
@all-contributors please add @madhavmehndiratta for code

**Pull request merged**
