### PR TITLE
Scientific Calculator GUI Added

### LINKED ISSUE #561: Scientific Calculator in Python
# Description

I want to add a GUI Scientific Calculator script in python.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by lavish619**
# Description

The Pull request contains the script of the Scientific calculator GUI made in Tkinter python.  
There are both options for standard and scientific calculators.  

Fixes #561 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by tusharnankani — CHANGES_REQUESTED** [review]
The calculator works well! 👍🏻 

Please, fix the DeepSource errors.

**Comment by lavish619** [comment]
Actually, there were 2 errors in DeepSorce, one is module not used, But what is actually happening is that module is used in form of string, its there in string and later it will be used when the expression will get evaluated, I have used the eval() function because of which there are security issues. I am not able to get any alternative of that. So can you please help me out.

**Comment by AdityaJ7** [comment]
> Actually, there were 2 errors in DeepSorce, one is module not used, But what is actually happening is that module is used in form of string, its there in string and later it will be used when the expression will get evaluated, I have used the eval() function because of which there are security issues. I am not able to get any alternative of that. So can you please help me out.

Fixed

**Review by AdityaJ7 — APPROVED** [review]

**Comment by lavish619** [comment]
> > Actually, there were 2 errors in DeepSorce, one is module not used, But what is actually happening is that module is used in form of string, its there in string and later it will be used when the expression will get evaluated, I have used the eval() function because of which there are security issues. I am not able to get any alternative of that. So can you please help me out.
> 
> Fixed

Do I have to do something now, or the issue is fixed, and everything is okay? I am actually new to opensource so can you someone tell me what I have to do now.

**Comment by AdityaJ7** [comment]
@lavish619 No, you don't have to do anything now, you can create new issues though, your PR will be merged automatically after two approvals

**Review by tusharnankani — APPROVED** [review]

**Comment by tusharnankani** [comment]
@all-contributors please add @lavish619 for code

**Pull request merged**
