### PR TITLE
Updated Covid19 Dashboard app

### PR DESCRIPTION
**Pull request by Aravindha1234u**
# Description
Add a new project of Covid19 Dashboard with worldwide data with api.covid19api.com as data source.

Fixes #(15)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Its working fine functionality-wise just some minor adjustments are needed like you have to relocate this folder inside the Miscellaneous folder and please add comments in your code.

You can remove datetime from requirements.txt as it is inbuilt.

**Review by AdityaJ7 — APPROVED** [review]

**Review by tusharnankani — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors please add @Aravindha1234u  for code

**Comment by Aravindha1234u** [comment]
Thanks a Lot @AdityaJ7

**Comment by AdityaJ7** [comment]
@all-contributors please add @Aravindha1234u for code

**Review by chavarera — COMMENTED** [review]
Cool work bro contribution

**Pull request merged**
