### PR TITLE
Scrape algo trading articles from quant finance websites

### PR DESCRIPTION
**Pull request by shivanshsinghal107**
# Description

Implemented scraper to get top algo trading and mathematical finance articles.

Fixes #([373](https://github.com/Python-World/Python_and_the_Web/issues/373))

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [X] New feature (non-breaking change which adds functionality)

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
Hey, @shivanshsinghal107 thanks for the contribution but can you change the branch name from which you contributed cause it might cause some conflicts with the all-contributors bot, that kind of branch naming is used by the bot.

**Comment by shivanshsinghal107** [comment]
> Hey, @shivanshsinghal107 thanks for the contribution but can you change the branch name from which you contributed cause it might cause some conflicts with the all-contributors bot, that kind of branch naming is used by the bot.
> 
> Everything else is good 👍🏽

Okay, so should I create another branch or just do it in the master

**Review by tusharnankani — CHANGES_REQUESTED** [review]
The script works well! 👍🏻 

Changes:
- Please describe what your script does in the README.
- Describe the terms like quantopian and quantocracy for better understanding.

Suggestion:
- Instead of printing in on the terminal, save it in a file, probably a .txt file.
- If you do so, add a sample .txt file in the folder as well.

**Comment by shivanshsinghal107** [comment]
> The script works well! 👍🏻
> 
> Changes:
> 
> * Please describe what your script does in the README.
> * Describe the terms like quantopian and quantocracy for better understanding.
> 
> Suggestion:
> 
> * Instead of printing it on the terminal, save it in a file, probably a .txt file.
> * If you do so, add a sample .txt file in the folder as well.

Okay

**Comment by shivanshsinghal107** [comment]
> The script works well! 👍🏻
> 
> Changes:
> 
> * Please describe what your script does in the README.
> * Describe the terms like quantopian and quantocracy for better understanding.
> 
> Suggestion:
> 
> * Instead of printing it on the terminal, save it in a file, probably a .txt file.
> * If you do so, add a sample .txt file in the folder as well.

All changes done, you can review then at pull [384](https://github.com/Python-World/Python_and_the_Web/pull/384).

**Pull request closed without merging**
