### PR TITLE
Simple PGM image processing added.

### LINKED ISSUE #566: Simple PGM image processing.
# Description

I want to add a script that works with PGM Images, doing some simple processing.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by SeaSkyThe**
# Description

Creating the script proposed on the cited issue (PGM Processing).

Fixes #566 

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Hi, @SeaSkyThe thanks for the contribution can you please fix the issues pointed out by DeepSource also can you please uncommit the .pgm file and add a way to include it through some website/source of pgm file in the README,md file

**Comment by SeaSkyThe** [comment]
> Hi, @SeaSkyThe thanks for the contribution can you please fix the issues pointed out by DeepSource also can you please uncommit the .pgm file and add a way to include it through some website/source of pgm file in the README,md file

Sure, im gonna try it!

**Comment by SeaSkyThe** [comment]
I think that it's done, can you check? Thanks for the tips!

**Review by AdityaJ7 — APPROVED** [review]

**Review by tusharnankani — APPROVED** [review]

**Comment by tusharnankani** [comment]
@all-contributors please add @SeaSkyThe for code

**Pull request merged**
