### PR TITLE
Added Reset and UI changes in Pong Game

### PR DESCRIPTION
**Pull request by wolflegend99**
- Added functionality for reset game after Game over
- Some Paddle UI changes to look cool

# Description

Added code for reset functionality after game over
Added some UI changes for game

Fixes #(issue_no)

Existing changes, no fixes

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
> This works properly for Python 3.8
> Please look into the matter of why the Deepsource is generating errors!

Dont worry about deepsource

**Comment by AdityaJ7** [comment]
> This works properly for Python 3.8
> Please look into the matter of why the Deepsource is generating errors!

When you are creating a PR please follow the steps which are mentioned in the README, that includes creating a separate branch for the changes that you are making

**Comment by wolflegend99** [comment]
> 
> When you are creating a PR please follow the steps which are mentioned in the README, that includes creating a separate branch for the changes that you are making

Actually, I wasn't addressing any issue as such. I just saw the code for the pong game in pygame and decided to make it more flexible and clean, hence I refactored it a bit.
Since I wasn't addressing any issue, I didn't create a separate branch :)

**Comment by AdityaJ7** [comment]
@all-contributors please add @wolflegend99 for code

**Pull request merged**
