### PR TITLE
Added python script for a Research paper latex parser

### PR DESCRIPTION
**Pull request by priya-mane**
# Description

A short summary of what is included in your Pull Request.

Fixes #31  

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Just add a few comments in the code(on hard to understand areas ) else everything is good
And add a requirements.txt file for the external libraries used and therefore update the section of readme where u  mentioned individual library installation to 
  `pip install -r requirements.txt`

**Comment by priya-mane** [comment]
> Just add a few comments in the code(on hard to understand areas ) else everything is good
> And add a requirements.txt file for the external libraries used and therefore update the section of readme to -- `pip install -r requirements.txt`

Okay, will do that.
Thanks!

**Comment by priya-mane** [comment]
> > Just add a few comments in the code(on hard to understand areas ) else everything is good
> > And add a requirements.txt file for the external libraries used and therefore update the section of readme to -- `pip install -r requirements.txt`
> 
> Okay, will do that.
> Thanks!

Have added comments and a requirements.txt file.Please review the same.
Thank you!

**Review by AdityaJ7 — APPROVED** [review]

**Review by tusharnankani — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@allcontributors please add @priya-mane for code

**Pull request merged**
