### PR TITLE
Turtle clock

### PR DESCRIPTION
**Pull request by ADV1K**
A simple Analog Clock Made with Python Turtle
python_q3BbSinMp1

### CODE REVIEW

**Review by chavarera — CHANGES_REQUESTED** [review]
remove cache files

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Remove files which are not related to this PR, your final or must contain -

- your main and helper scripts
- a screenshot of the script in action
- a requirements.txt file if required
- a README.md file

# Please from next time don't clear the PR template, it consists of guidelines that your pr must follow.

**Review by tusharnankani — CHANGES_REQUESTED** [review]
Hi @ADV1K 

- You have opened a lot of PRs lately. We like the spirit, but not the spam.
- The PRs you have created till now **does not** follow the [Contributing.md](https://github.com/Python-World/Python_and_the_Web/blob/master/CONTRIBUTING.md) or the given templates.

- The PRs from the 15 puzzles game till now, the files have been adding on to all the PRs.
- This is probably because you have either committing from the same branch or creating a new branch from the previously created new branch.

Solutions:
- Don't touch the master branch ever in your fork. 
- Always *create a new branch* from **master.** Checkout to master before creating a new branch.

Possible solutions to fix this: 
- Either you uncommit all these files from respective branches.
OR
- We close all your PRs and you create PRs from Scratch, neatly and properly.

**Comment by ADV1K** [comment]
created a new clean PR so im closing this one.

**Comment by ADV1K** [comment]
> Hi @ADV1K
> 
> * You have opened a lot of PRs lately. We like the spirit, but not the spam.
> * The PRs you have created till now **does not** follow the [Contributing.md](https://github.com/Python-World/Python_and_the_Web/blob/master/CONTRIBUTING.md) or the given templates.
> * The PRs from the 15 puzzles game till now, the files have been adding on to all the PRs.
> * This is probably because you have either committing from the same branch or creating a new branch from the previously created new branch.
> 
> Solutions:
> 
> * Don't touch the master branch ever in your fork.
> * Always _create a new branch_ from **master.** Checkout to master before creating a new branch.
> 
> Possible solutions to fix this:
> 
> * Either you uncommit all these files from respective branches.
>   OR
> * We close all your PRs and you create PRs from Scratch, neatly and properly.

Thank you I Found out my mistake. it was happening because i was creating new branches without checking out to master

**Pull request closed without merging**
