### PR TITLE
Movie Recommender

### LINKED ISSUE #457: Movie Recommender
# Description

I would like to add a python program for Movie Recommendation using tastedive and OMDB APIs

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [x] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by aakashdinkar**
# Description

I have added a program for movie recommendation for issue #457  

Fixes #457 

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
Hey @aakashdinkar just add a requirements.txt file with the requests module in it  and we'll merge it

**Comment by aakashdinkar** [comment]
@AdityaJ7  ok i'll add requirements.txt

**Comment by aakashdinkar** [comment]
@AdityaJ7 I have added requirements.txt

**Comment by AdityaJ7** [comment]
@all-contributors please add @aakashdinkar for code

**Pull request merged**
