### PR TITLE
Script to convert JSON to EXCEL 

### PR DESCRIPTION
**Pull request by Meghana-12**
# Description

This PR includes py script to convert JSON file to excel file. 

Fixes #(issue_no)

#35

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
The requirements.txt file should only contain this:

pandas==1.1.2

Everything else works fine nice work

**Comment by Meghana-12** [comment]
Sure, I'll update that!

**Comment by AdityaJ7** [comment]
> Sure, I'll update that!

The heading in your readme file is incorrect please check that

**Comment by Meghana-12** [comment]
> > Sure, I'll update that!
> 
> The heading in your readme file is incorrect please check that

Updated it just now!

**Review by AdityaJ7 — APPROVED** [review]

**Review by tusharnankani — APPROVED** [review]

**Comment by AdityaJ7** [comment]
@all-contributors-bot please add @Meghana-12 for code

**Comment by AdityaJ7** [comment]
@all-contributors please add @Meghana-12 for code

**Pull request merged**
