### PR TITLE
Activation Functions from Scratch in Keras

### LINKED ISSUE #101: Activation Functions from Scratch in Keras
#31 Activation Functions from Scratch in Keras

In the following project, we experiment and  implement activation functions commonly used in deep learning libraries from scratch using Keras and Tensorflow

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by Agrover112**
# Activation Functions from Scratch in Keras

In the following project, we experiment and try to implement activation functions commonly used in deep learning libraries from scratch using Keras and Tensorflow

Fixes #101

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by chavarera — CHANGES_REQUESTED** [review]
references/README.md is outside from your project scope remove it

**Comment by Agrover112** [comment]
wait

**Comment by Agrover112** [comment]
@chavarera  Done

**Comment by AdityaJ7** [comment]
> @chavarera Done

Now, its done

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Just add some comments in your utils.py file and we'll merge it

Good Job @Agrover112

**Comment by Agrover112** [comment]
@AdityaJ7  Changes made

**Review by AdityaJ7 — APPROVED** [review]

**Review by chavarera — APPROVED** [review]

**Comment by Agrover112** [comment]
Thanks

**Comment by AdityaJ7** [comment]
@all-contributors please add @Agrover112 for code

**Pull request merged**
