### PR TITLE
Automatic Birthday Wisher

### PR DESCRIPTION
**Pull request by chhipashubham970**
# Description

Python script to automate the birthday wishes send to your friends. 
The script will run every day at 12:00 AM and check that is there any birthday of your friend you mentioned in the excel sheet and if there is a birthday then the script will automatically send the email to your friends.

Link to the issue 👍 https://github.com/Python-World/Python_and_the_Web/issues/31#issuecomment-702506234

### CODE REVIEW

**Review by tusharnankani — CHANGES_REQUESTED** [review]
Please remove unnecessary blank lines!
Add a screenshot of the working script and the email sent, for the viewer's reference.

**Comment by chhipashubham970** [comment]
Yeah sure, I will do changes.
I have one question that after making changes in my forked repository I have to make a pull request again.

**Comment by AdityaJ7** [comment]
> Yeah sure, I will do changes.
> I have one question that after making changes in my forked repository I have to make a pull request again.

No just make the changes and commit them it will be automatically updated in your Pull Request

**Comment by chhipashubham970** [comment]
ok thanks

**Comment by chhipashubham970** [comment]
Change is done. Please review and tell me if there are any changes.

**Comment by AdityaJ7** [comment]
@all-contributors please add @chhipashubham970 for code

**Comment by chhipashubham970** [comment]
Thanks for merging my pull request.

**Pull request merged**
