### PR TITLE
Python script that provides the download and upload speed of your Wifi

### LINKED ISSUE #37: Wifi Speed tester with Python
# Description

Create a script that provides the download and upload speed of your Wifi.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by AdeshChoudhar19**
# Description

A short summary of what is included in your Pull Request.

Fixes #37 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
Hi @AdeshChoudhar19 thanks for creating this pull request you need to create two more files:

1. Readme file(describes your script)
2. requirements.txt file(contains the external libraries used by you)

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Please make the requested changes.

**Review by tusharnankani — CHANGES_REQUESTED** [review]
Please follow [these steps]( https://github.com/Python-World/Python_and_the_Web#steps-to-follow), and add the required files.

**Comment by AdeshChoudhar19** [comment]
Please check the pull request.

**Comment by AdityaJ7** [comment]
> Please check the pull request.

Works fine though your while loop is not working properly, it must keep asking the user for an option until they hit 3
and when they hit 3 it must end the program while right now even after pressing 3 it does not end the program

**Comment by AdeshChoudhar19** [comment]
Sorry for silly mistakes, it's my first pull request. I have made the necessary changes.

**Comment by AdeshChoudhar19** [comment]
It is exiting the loop, it is there in screenshot.

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
requirements file must contain only this::

speedtest-cli==2.1.2

**Comment by AdityaJ7** [comment]
> It is exiting the loop, it is there in screenshot.

You didn't get my point, I am saying that it must keep asking the user for an option until they hit 3

**Comment by AdityaJ7** [comment]
> Sorry for silly mistakes, it's my first pull request. I have made the necessary changes.

It's ok

**Comment by AdeshChoudhar19** [comment]
I'm getting your point but I think it is happening the way you wanted, please see  the screenshot again or try again.

**Comment by AdityaJ7** [comment]
> I'm getting your point but I think it is happening the way you wanted, please see the screenshot again or try again.

Capture


See this is the screenshot that u sent, In this  when you used option 1  the script got exit, which must  not happen
Script must exit only on option 3
and it must keep aksig the user to enter an option until they enter 3

**Comment by AdeshChoudhar19** [comment]
Yes, I got it now.
2 minutes.

**Review by tusharnankani — APPROVED** [review]

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
Works Fine now @AdeshChoudhar19  Congrats on your first Pull request

**Comment by AdeshChoudhar19** [comment]
Thank you so much! You guys are very helpful and approachable! I consider myself lucky to have you as mentors. Thanks again!

**Comment by AdeshChoudhar19** [comment]
So what's next? Do I have to close the issue or you guys do?

**Comment by AdityaJ7** [comment]
> Thank you so much! You guys are very helpful and approachable! I consider myself lucky to have you as mentors. Thanks again!

It's ok bro, everyone here is learning!!

**Comment by AdityaJ7** [comment]
> So what's next? Do I have to close the issue or you guys do?

We'll do it.

**Comment by AdeshChoudhar19** [comment]
Merged finally! I will look forward to work with you again!

**Comment by AdeshChoudhar19** [comment]
Github said, do you want to delete the forked repository. What should I do?

**Comment by AdityaJ7** [comment]
> Github said, do you want to delete the forked repository. What should I do?

Delete it if you don't want to contribute here anymore, but if want to contribute in the future than u must not delete it

**Comment by AdeshChoudhar19** [comment]
Ok. Thanks.

**Comment by AdityaJ7** [comment]
@all-contributors please add @AdeshChoudhar19  for code

**Comment by AdeshChoudhar19** [comment]
Can you tell me what happened now?

**Comment by AdityaJ7** [comment]
> Can you tell me what happened now?

nothing you don't have to worry about it

**Comment by tusharnankani** [comment]
Hi @AdeshChoudhar19 

> Can you tell me what happened now?

We are adding you to the [Contributors](https://github.com/Python-World/Python_and_the_Web#contributors-), so our very own, `allcontributors` bot opens a PR for us, for you #62 was merged. 

Congratulations! Looking forward to more contributions from your end! ^_^

**Comment by AdeshChoudhar19** [comment]
Yes, sure!

**Comment by AdeshChoudhar19** [comment]
You have added the hacktoberfest-accepted label, but still, my pull request is being shown in review. Can you tell me why this is happening?

**Comment by AdityaJ7** [comment]
> You have added the hacktoberfest-accepted label, but still, my pull request is being shown in review. Can you tell me why this is happening?

that review period is set by Digital ocean, it will end 14 days after your or has been approved, don't worry.

**Comment by AdeshChoudhar19** [comment]
Ok. Thank you.

**Pull request merged**
