### PR TITLE
Road lane detection

### LINKED ISSUE #250: Road Lanes Detection
# Description

 Detecting road lanes using Python and OpenCV

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by adityagandhamal**
# Description

Python scripts which detect road lanes both in an image and in video frames.

Fixes #250 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
@adityagandhamal  please remove the videos, only keep working screenshots

**Comment by adityagandhamal** [comment]
Alright, i will do it.

**Comment by adityagandhamal** [comment]
@AdityaJ7 I have successfully removed the videos and replaced them with the working screenshots.

**Comment by adityagandhamal** [comment]
@AdityaJ7 I have removed all the video files.

**Comment by AdityaJ7** [comment]
@all-contributors please add @adityagandhamal for code

**Pull request merged**
