### PR TITLE
Cricket scrapper

### LINKED ISSUE #6: Script to scrape cricketer information
# Description

Create a script that will take the name of a cricketer as input and will return the information related to him/her like total runs, wickets, strike rate, economy , etc.

## Type of issue

- [x] Feature(New Script)
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects before submitting a new project issue
- [x] I have checked previous issues to avoid duplicates
- [x] This issue will be meaningful for the project.

### PR DESCRIPTION
**Pull request by varuntumbe**
# Description

Given the first name and last name of a cricketer this script scrapes wikipedia and gives personal and career information about cricketer.

Fixes #6 

issue_no

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Excellent Job @varuntumbe 

Just a minor suggestion -- it will be nice if the text file that is saved after the execution of the program should have a name same as the name of the cricketer

**Comment by varuntumbe** [comment]
sure will change it now.

**Review by AdityaJ7 — APPROVED** [review]
God job

**Comment by AdityaJ7** [comment]
@all-contributors please add @varuntumbe for code

**Comment by varuntumbe** [comment]
Thanks @AdityaJ7  learnt a lot on git.

**Pull request merged**
