### PR TITLE
Added Google Search Script

### PR DESCRIPTION
**Pull request by nj1902**
# Description

Script showing search results of google search.

Fixes #(#90 )

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Review by AdityaJ7 — CHANGES_REQUESTED** [review]
Please comment your code and follow the functional programming paradigm and include a requirements.txt file which contains the google module.

Also, add a prompt message in the input

**Comment by naazneen** [comment]
Hello, I would like to contribute on this script.

**Comment by AdityaJ7** [comment]
> Hello, I would like to contribute on this script.

Ah, @naazneen thanks for your interest but @nj1902 is working on it.

You can check the projects that are already present in our repos - this one and the python-min-project repo and submit an issue for a script that you want to add and is not already present.

For any other query drop a comment [here](https://github.com/Python-World/Python_and_the_Web/issues/31) or in our WhatsApp group

Thanks

**Comment by nj1902** [comment]
Pl. Review updated PR.

**Review by tusharnankani — APPROVED** [review]

**Review by AdityaJ7 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
all-contributors please add @nj1902 for code

**Comment by AdityaJ7** [comment]
@all-contributors please add @nj1902 for code

**Pull request merged**
