### PR TITLE
Added Instagram Analyzer

### PR DESCRIPTION
**Pull request by yogeshwaran01**
# Description

Added Instagram Analyzer, Which analyzes the Instagram user data like followers, followings, and posts with Matplotlib.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

### CODE REVIEW

**Comment by AdityaJ7** [comment]
HI @yogeshwaran01 i don't think this is a web scrapper so change the location of your folder to Miscellaneous

**Comment by yogeshwaran01** [comment]
ok

**Comment by yogeshwaran01** [comment]
@AdityaJ7 Location changed

**Review by tusharnankani — APPROVED** [review]
The script works well! 
Expecting more contributions from your end! ^_^
Keep it up @yogeshwaran01 👍🏻

**Comment by tusharnankani** [comment]
@all-contributors please add @yogeshwaran01 for code

**Pull request merged**
